---

stages:
  - prepare-api
  - build-api
  - deploy-api
  
prepare-api:
  image: ruby:2.6-alpine
  stage: prepare-api
  script:
    - pwd
    - ls -l
    - $CI_BUILDS_DIR/api/encrypt_secrets.rb production

build-api:
  image: java:8-jdk-alpine
  stage: build-api
  script:
    - cd api
    - api/gradlew clean build
    
deploy-api:
  image: google/cloud-sdk:alpine
  stage: deploy-api
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud init
    - gcloud auth activate-service-account --key-file=/tmp/$CI_PIPELINE_ID.json --project=wortschatz
    - gcloud components install beta
    - gcloud components update
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    - cd $CI_BUILDS_DIR/api && docker build . --tag gcr.io/wortschatz-rockyj/wortschatz-api
    - docker push gcr.io/wortschatz-rockyj/wortschatz-api
    - gcloud beta run deploy wortschatz-api --image gcr.io/wortschatz-rockyj/wortschatz-api
