---

stages:
  - prepare-api
  - build-api
  - deploy-api
  
prepare-api:
  image: ruby:2.6-alpine
  stage: prepare-api
  script:
    - mkdir -p $CI_PROJECT_DIR/api/src/main/resources/secrets
    - echo $SECRETS_YAML > $CI_PROJECT_DIR/api/src/main/resources/secrets/secrets.yaml
    - cd $CI_PROJECT_DIR/api && ruby encrypt_secrets.rb production

build-api:
  image: java:8-jdk-alpine
  stage: build-api
  script:
    - cd $CI_PROJECT_DIR/api && ./gradlew -Dorg.gradle.daemon=false clean build --info
    
deploy-api:
  image: google/cloud-sdk:alpine
  stage: deploy-api
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud init
    - gcloud auth activate-service-account --key-file=/tmp/$CI_PIPELINE_ID.json --project=wortschatz
    - gcloud components install beta
    - gcloud components update
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    - cd $CI_PROJECT_DIR/api && docker build . --tag gcr.io/wortschatz-rockyj/wortschatz-api
    - docker push gcr.io/wortschatz-rockyj/wortschatz-api
    - gcloud beta run deploy wortschatz-api --image gcr.io/wortschatz-rockyj/wortschatz-api
