---

stages:
  - prepare-api
  - build-api
  - deploy-api
  
prepare-api:
  image: ruby:2.6-alpine
  stage: prepare-api
  script:
    - mkdir -p $CI_PROJECT_DIR/api/src/main/resources/secrets
    - echo $SECRETS_YAML > $CI_PROJECT_DIR/api/src/main/resources/secrets/secrets.yaml
    - cd $CI_PROJECT_DIR/api && ruby encrypt_secrets.rb production

build-api:
  image: java:8-jdk
  stage: build-api
  cache:
    paths:
      - .gradle
  script:
    - cd $CI_PROJECT_DIR/api && ./gradlew -Dorg.gradle.daemon=false clean build --info
    
deploy-api:
  image: google/cloud-sdk
  stage: deploy-api
  script:
    - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud config set run/region us-central1
    - gcloud config set project wortschatz
    - gcloud auth activate-service-account --key-file=/tmp/$CI_PIPELINE_ID.json
    - gcloud components install beta
    - gcloud components update
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    - cd $CI_PROJECT_DIR/api && docker build . --tag gcr.io/wortschatz-rockyj/wortschatz-api
    - docker push gcr.io/wortschatz-rockyj/wortschatz-api
    - gcloud beta run deploy wortschatz-api --image gcr.io/wortschatz-rockyj/wortschatz-api
